title: Vinwjin Lab
description: 折腾记录 & 经验分享 - AI、NAS、技术宅
theme: jekyll-theme-minima

url: https://vinwjin.github.io
baseurl: ""
permalink: /posts/:title/

author:
  name: Vinwjin
  email: vinwjin@github.com

github_username: vinwjin

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 10
paginate_path: "/page:num/"
